const http = require("http");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const mime = {
  ".html": "text/html",
  ".css": "text/css",
  ".js": "text/javascript",
  ".md": "text/plain",
  ".json": "application/json",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
};

// ---- load .env (simple parser, no deps) ----
const env = {};
try {
  for (const line of fs.readFileSync(path.join(__dirname, ".env"), "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m && !line.trim().startsWith("#")) env[m[1]] = m[2].trim();
  }
} catch { /* no .env — fine, demo mode */ }

// ---- /config.js endpoint: injects the key, never exposes .env itself ----
const hostList = (env.VIDSRC_HOSTS || "vidsrc.to,vidsrc.cc")
  .split(",").map(s => s.trim()).filter(Boolean);

let demoArt = null;
try { demoArt = require("./posters.cjs"); } catch { /* optional */ }

const configScript = `// generated by server.js from your local .env — do not edit
window.AF_ENV = {
  tmdbKey: ${JSON.stringify(env.TMDB_API_KEY && env.TMDB_API_KEY !== "your_tmdb_v3_api_key_here" ? env.TMDB_API_KEY : "")},
  vidsrcHosts: ${JSON.stringify(hostList)},
  imgProxy: true,
  demoArt: ${JSON.stringify(demoArt || null)}
};`;

// ---- /img proxy: fetch TMDB images server-side with a disk cache ----
// Some browsers/network setups block image.tmdb.org directly; same-origin proxy avoids that.
const IMG_CACHE = path.join(__dirname, ".cache", "img");

async function handleImg(req, res) {
  const qs = new URL(req.url, "http://x").searchParams;
  const target = qs.get("u") || "";
  let parsed;
  try { parsed = new URL(target); } catch { res.writeHead(400); res.end(); return; }
  if (parsed.protocol !== "https:" || parsed.hostname !== "image.tmdb.org" || !parsed.pathname.startsWith("/t/p/")) {
    res.writeHead(400); res.end(); return;
  }
  const extMatch = parsed.pathname.match(/\.(jpg|jpeg|png|webp|gif)$/i);
  const ext = extMatch ? extMatch[0] : ".jpg";
  const type = ext === ".png" ? "image/png" : ext === ".webp" ? "image/webp" : ext === ".gif" ? "image/gif" : "image/jpeg";
  const cacheFile = path.join(IMG_CACHE, crypto.createHash("md5").update(target).digest("hex") + ext);

  const serve = (buf) => {
    res.writeHead(200, { "Content-Type": type, "Cache-Control": "public, max-age=604800" });
    res.end(buf);
  };

  try { serve(fs.readFileSync(cacheFile)); return; } catch { /* cache miss */ }
  const placeholder = () => {
    const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='500' height='750'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#1b1440'/><stop offset='.55' stop-color='#0e2038'/><stop offset='1' stop-color='#0d1020'/></linearGradient></defs><rect width='500' height='750' fill='url(#g)'/><circle cx='110' cy='130' r='150' fill='rgba(124,58,237,0.28)'/><circle cx='420' cy='650' r='170' fill='rgba(34,211,238,0.18)'/><text x='250' y='380' font-size='64' text-anchor='middle'>🎬</text><text x='250' y='445' font-size='20' letter-spacing='6' text-anchor='middle' fill='#8f97bd' font-family='sans-serif'>AURAFLEX</text></svg>`;
    res.writeHead(200, { "Content-Type": "image/svg+xml", "Cache-Control": "public, max-age=3600" });
    res.end(svg);
  };
  try {
    const r = await fetch(target, { headers: { "User-Agent": "auraflex/1.0" } });
    if (!r.ok) { placeholder(); return; }
    const ctype = r.headers.get("content-type") || type;
    if (!ctype.startsWith("image/")) { res.writeHead(415); res.end(); return; }
    const buf = Buffer.from(await r.arrayBuffer());
    try {
      fs.mkdirSync(IMG_CACHE, { recursive: true });
      fs.writeFileSync(cacheFile, buf);
    } catch { /* cache write is best-effort */ }
    serve(buf);
  } catch {
    placeholder();
  }
}

// ---- /canary: is a playback host reachable from THIS network? (honest check, no masking) ----
const canaryCache = new Map();

async function handleCanary(req, res) {
  const host = new URL(req.url, "http://x").searchParams.get("host") || "";
  if (!/^[a-z0-9.-]+$/i.test(host)) { res.writeHead(400); res.end(); return; }
  const c = canaryCache.get(host);
  if (c && Date.now() - c.t < 5 * 60 * 1000) {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify(c));
    return;
  }
  let result;
  try {
    const ac = new AbortController();
    const timer = setTimeout(() => ac.abort(), 4000);
    const r = await fetch(`https://${host}/`, { signal: ac.signal, headers: { "User-Agent": "auraflex/1.0" } });
    clearTimeout(timer);
    result = { t: Date.now(), ok: r.status < 500, status: r.status };
  } catch {
    result = { t: Date.now(), ok: false, status: 0 };
  }
  canaryCache.set(host, result);
  res.writeHead(200, { "Content-Type": "application/json" });
  res.end(JSON.stringify(result));
}

const server = http.createServer((req, res) => {
  let p = decodeURIComponent(req.url.split("?")[0]);
  if (p === "/") p = "/index.html";

  // HTML must never be cached — stale shells were serving pre-fix JS
  if (p.endsWith(".html")) {
    const htmlFile = path.join(__dirname, path.normalize(p));
    if (!htmlFile.startsWith(__dirname)) { res.writeHead(403); res.end(); return; }
    fs.readFile(htmlFile, (err, data) => {
      if (err) { res.writeHead(404); res.end(); return; }
      res.writeHead(200, { "Content-Type": mime[".html"], "Cache-Control": "no-store" });
      res.end(data);
    });
    return;
  }

  // block .env and dotfiles explicitly
  if (p.includes("/.env") || /\/\.\w/.test(p)) {
    res.writeHead(403);
    res.end("forbidden");
    return;
  }

  if (p === "/config.js") {
    res.writeHead(200, { "Content-Type": mime[".js"], "Cache-Control": "no-store" });
    res.end(configScript);
    return;
  }

  if (p === "/img") {
    handleImg(req, res);
    return;
  }

  if (p === "/canary") {
    handleCanary(req, res);
    return;
  }

  const file = path.join(__dirname, path.normalize(p));
  if (!file.startsWith(__dirname)) {
    res.writeHead(403);
    res.end("forbidden");
    return;
  }

  fs.readFile(file, (err, data) => {
    if (err) {
      res.writeHead(404);
      res.end("not found");
      return;
    }
    // never cache HTML/JS/CSS — avoids stale app shells after edits; images are cached separately
    const noCache = /\.(html|js|css)$/i.test(file);
    res.writeHead(200, {
      "Content-Type": mime[path.extname(file)] || "application/octet-stream",
      "Cache-Control": noCache ? "no-cache" : "public, max-age=86400",
    });
    res.end(data);
  });
});

const PORT = Number(process.env.PORT) || 8788;
server.listen(PORT, () => console.log(`AURAFLEX running → http://localhost:${PORT}`));
