// Vercel serverless function: /api/config (CommonJS — matches package.json, no "type":"module")
// Serves the same generated config as the local server's /config.js,
// reading the key from the TMDB_API_KEY environment variable.
module.exports = (req, res) => {
  try {
    const key = (process.env.TMDB_API_KEY || "").trim();
    const hosts = (process.env.VIDSRC_HOSTS || "vidsrc.to,vidsrc.cc")
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);

    const cfg = {
      tmdbKey: key && key !== "your_tmdb_v3_api_key_here" ? key : "",
      vidsrcHosts: hosts.length ? hosts : ["vidsrc.to", "vidsrc.cc"],
      imgProxy: true,
      demoArt: null,
    };

    res.setHeader("Content-Type", "application/javascript");
    res.setHeader("Cache-Control", "no-store");
    res.status(200).send(
      `// generated by /api/config from deployment env — do not edit\nwindow.AF_ENV = ${JSON.stringify(cfg)};`
    );
  } catch {
    // never 500 — worst case, boot in demo mode
    res.setHeader("Content-Type", "application/javascript");
    res.status(200).send('window.AF_ENV = { tmdbKey: "", vidsrcHosts: ["vidsrc.to","vidsrc.cc"], imgProxy: true, demoArt: null };');
  }
};
